name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04
    
    strategy:
      matrix:
        board: [MDBT42Q, PUCKJS, BANGLEJS, BANGLEJS2]

    steps:
    - uses: actions/checkout@v2
    - name: make ${{ matrix.board }}
      env:
        TRAVIS: 1
        RELEASE: 1
        BOARD: ${{ matrix.board }}    
      run: |
        source ./scripts/provision.sh  ${{ matrix.board }}
        make
 
# Disable doc building for now 
#  docs:
#    runs-on: ubuntu-20.04      
#    steps:
#    - name: makedocs
#      run: make docs
